from locust import HttpUser, between, task

# Try to read the token generated by setup_test_data.py
try:
    with open(".loadtest_token") as f:
        TOKEN = f.read().strip()
except FileNotFoundError:
    print("WARNING: .loadtest_token file not found. Did you run setup_test_data.py?")
    TOKEN = "missing_token"


class ScalableUserBehavior(HttpUser):
    # Wait between 0.5 to 2 seconds between tasks
    wait_time = between(0.5, 2.0)

    def on_start(self):
        """Called when a Locust user starts before any task is scheduled"""
        self.client.headers.update({"Authorization": f"Bearer {TOKEN}", "Content-Type": "application/json"})

    @task(3)
    def get_me(self):
        """Simulate fetching the user profile (Hits Redis cache, or DB)"""
        self.client.get("/api/v1/users/me", name="/api/v1/users/me")

    @task(1)
    def check_health(self):
        """Simulate a load balancer health check"""
        self.client.get("/health/ready", name="/health/ready")

    @task(1)
    def failed_login(self):
        """Simulate a failed login attempt (Tests bcrypt hashing CPU load & account lockout)"""
        # We use the valid loadtest user but a wrong password to avoid the short-circuit optimization!
        self.client.post(
            "/api/v1/users/login",
            json={"email": "loadtest@example.com", "password": "WrongPassword"},
            name="/api/v1/users/login (Failed)",
        )
